services:
  app:
    build: 
      context: ./security2FAC
      dockerfile: Dockerfile
    image: 2factor-service:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=2factor_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 2factor_db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge

volumes:
  postgres:
